package com.example.news_app.Helpers

class NewsOptionsHelper {
    companion object{
        val countries = mapOf(
            "Any" to null,
            "Argentina" to "ar",
            "Australia" to "au",
            "Austria" to "at",
            "Belgium" to "be",
            "Brazil" to "br",
            "Bulgaria" to "bg",
            "Canada" to "ca",
            "China" to "cn",
            "Colombia" to "co",
            "Cuba" to "cu",
            "Czechia" to "cz",
            "Egypt" to "eg",
            "France" to "fr",
            "Germany" to "de",
            "Greece" to "gr",
            "Honk Kong" to "hk",
            "Hungary" to "hu",
            "Indonesia" to "id",
            "Ireland" to "ie",
            "Israel" to "il",
            "India" to "in",
            "Italy" to "it",
            "Japan" to "jp",
            "Korea" to "kr",
            "Latvia" to "lv",
            "Lithuania" to "lt",
            "Morocco" to "ma",
            "Mexico" to "mx",
            "Malaysia" to "my",
            "Nigeria" to "ng",
            "Netherlands" to "nl",
            "Norway" to "no",
            "New Zealand" to "nz",
            "Philippines" to "ph",
            "Poland" to "pl",
            "Portugal" to "pt",
            "Romania" to "ro",
            "Russia" to "ru",
            "Serbia" to "rs",
            "Saudi Arabia" to "sa",
            "Sweden" to "se",
            "Singapore" to "sg",
            "Slovenia" to "si",
            "Slovakia" to "sk",
            "South Africa" to "za",
            "Switzerland" to "ch",
            "Thailand" to "th",
            "Turkey" to "tr",
            "Taiwan" to "tw",
            "Ukraine" to "ua",
            "United Arab Emirates" to "ae",
            "United Kingdom of Great Britain and Northern Ireland" to "gb",
            "USA" to "us",
            "Venezuela" to "ve"
        )

        val languages = mapOf(
            "Any" to null,
            "Arabic" to "ar",
            "Chinese" to "zh",
            "Dutch" to "nl",
            "English" to "en",
            "French" to "fr",
            "German" to "de",
            "Hebrew" to "he",
            "Italian" to "it",
            "Norwegian" to "no",
            "Portuguese" to "pt",
            "Russian" to "ru",
            "Sami" to "se",
            "Spanish" to "es",
        )
    }
}